apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "kube-state-metrics"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app.kubernetes.io/name: "kube-state-metrics"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - backend:
            serviceName: kube-state-metrics
            servicePort: 8080
          path: /kube-state-metrics(/|$)(.*)
